version: '3.8'

services:
  web:
    image: ghcr.io/we-meetting/wemeet-backend:latest
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wemeet
      MYSQL_USER: choi138
      MYSQL_PASSWORD: wemeet1234
      MYSQL_ROOT_PASSWORD: wemeet1234
      TZ: Asia/Seoul
    restart: always

networks:
  app-network:

volumes:
  mysql:
